config/routes.rb
Rails.application.routes.draw do
  
    root 'patients#index'
  
  # get 'static_pages/home'

    #get 'signup'
    get 'static_pages/sign_up'
    get 'static_pages/sign_in'
    get 'users/new'
  
    resources :doctor_notes
  #resources :microposts
    resources :patients
    resources :users
  
end

app/models/doctor_note.rb
class DoctorNote < ApplicationRecord
    belongs_to :patient
    validates :content, length: { maximum: 120},
                        presence: true
end

app/controllers/doctor_notes_controller.rb
class DoctorNotesController < ApplicationController
  before_action :set_doctor_note, only: [:show, :edit, :update, :destroy]

  # GET /doctor_notes
  # GET /doctor_notes.json
  def index
    @doctor_notes = DoctorNote.all
  end

  # GET /doctor_notes/1
  # GET /doctor_notes/1.json
  def show
  end

  # GET /doctor_notes/new
  def new
    @doctor_note = DoctorNote.new
  end

  # GET /doctor_notes/1/edit
  def edit
  end

  # POST /doctor_notes
  # POST /doctor_notes.json
  def create
    @doctor_note = DoctorNote.new(doctor_note_params)

    respond_to do |format|
      if @doctor_note.save
        format.html { redirect_to @doctor_note, notice: 'Doctor note was successfully created.' }
        format.json { render :show, status: :created, location: @doctor_note }
      else
        format.html { render :new }
        format.json { render json: @doctor_note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctor_notes/1
  # PATCH/PUT /doctor_notes/1.json
  def update
    respond_to do |format|
      if @doctor_note.update(doctor_note_params)
        format.html { redirect_to @doctor_note, notice: 'Doctor note was successfully updated.' }
        format.json { render :show, status: :ok, location: @doctor_note }
      else
        format.html { render :edit }
        format.json { render json: @doctor_note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctor_notes/1
  # DELETE /doctor_notes/1.json
  def destroy
    @doctor_note.destroy
    respond_to do |format|
      format.html { redirect_to doctor_notes_url, notice: 'Doctor note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor_note
      @doctor_note = DoctorNote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_note_params
      params.require(:doctor_note).permit(:content, :patient_id)
    end
end

app/helpers/doctor_notes_helper.rb
module DoctorNotesHelper
end

app/views/doctor_notes/_form.html.erb
<%= form_with(model: doctor_note, local: true) do |form| %>
  <% if doctor_note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(doctor_note.errors.count, "error") %> prohibited this doctor_note from being saved:</h2>

      <ul>
      <% doctor_note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="field">
    <%= form.label :patient_id %>
    <%= form.number_field :patient_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/doctor_notes/edit.html.erb
<h1>Editing Doctor Note</h1>

<%= render 'form', doctor_note: @doctor_note %>

<%= link_to 'Show', @doctor_note %> |
<%= link_to 'Back', doctor_notes_path %>

app/views/doctor_notes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Doctor Notes</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Patient</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doctor_notes.each do |doctor_note| %>
      <tr>
        <td><%= doctor_note.content %></td>
        <td><%= doctor_note.patient_id %></td>
        <td><%= link_to 'Show', doctor_note %></td>
        <td><%= link_to 'Edit', edit_doctor_note_path(doctor_note) %></td>
        <td><%= link_to 'Destroy', doctor_note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Doctor Note', new_doctor_note_path %>

app/views/doctor_notes/new.html.erb
<h1>New Doctor Note</h1>

<%= render 'form', doctor_note: @doctor_note %>

<%= link_to 'Back', doctor_notes_path %>

app/views/doctor_notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @doctor_note.content %>
</p>

<p>
  <strong>Patient:</strong>
  <%= @doctor_note.patient_id %>
</p>

<%= link_to 'Edit', edit_doctor_note_path(@doctor_note) %> |
<%= link_to 'Back', doctor_notes_path %>