config/routes.rb
Rails.application.routes.draw do
  
    root 'patients#index'
  
  # get 'static_pages/home'

    #get 'signup'
    get 'static_pages/sign_up'
    get 'static_pages/sign_in'
    get 'users/new'
  
    resources :doctor_notes
  #resources :microposts
    resources :patients
    resources :users
  
end

app/models/patient.rb
class Patient < ApplicationRecord
    
    # The code below is the search method functionality for the patient database
    def self.search(search)
        if search
            where(["last_name LIKE ?","%#{search}%"])
        else
             return all
        end
    end

    belongs_to :user
    has_many :doctor_notes
    
#form validation is required
    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :address, presence: true
    #validates :date_birth, presence: true
    validates :phone, presence: true
    validates :infection, presence: true
    validates :injury, presence: true
    validates :observation, presence: true
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  #Code below uses Patient.where to enable a search function to filter the list of patients in the database
  def index
    @patients = Patient.search(params[:search])
  end
  
  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:first_name, :last_name, :address, :date_birth, :phone, :infection, :injury, :observation)
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_with(model: patient, local: true) do |form| %>
  <% if patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :date_birth %>
    <%= form.date_select :date_birth %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :infection %>
    <%= form.text_field :infection %>
  </div>

  <div class="field">
    <%= form.label :injury %>
    <%= form.text_field :injury %>
  </div>

  <div class="field">
    <%= form.label :observation %>
    <%= form.text_field :observation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing Patient</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<div class="center jumbotron"
  <h1>Patients</h1>

<table class=table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Address</th>
      <th>Date birth</th>
      <th>Phone</th>
      <th>Infection</th>
      <th>Injury</th>
      <th>Observation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.first_name %></td>
        <td><%= patient.last_name %></td>
        <td><%= patient.address %></td>
        <td><%= patient.date_birth %></td>
        <td><%= patient.phone %></td>
        <td><%= patient.infection %></td>
        <td><%= patient.injury %></td>
        <td><%= patient.observation %></td>
        <td><%= link_to 'Show', patient %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<!--This is the search bar code that allows the user to -->
<!--end a value into the bar and filter the patient list-->

<%= form_tag patients_path, :method => 'get' do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search" %>
<% end %>


<br>

<%= link_to 'New Patient', new_patient_path, class: "btn btn-lg btn-primary" %>

<br>

<%= link_to "Add Doctors Notes", new_doctor_note_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/patients/new.html.erb
<h1>New Patient</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @patient.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @patient.last_name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @patient.address %>
</p>

<p>
  <strong>Date birth:</strong>
  <%= @patient.date_birth %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @patient.phone %>
</p>

<p>
  <strong>Infection:</strong>
  <%= @patient.infection %>
</p>

<p>
  <strong>Injury:</strong>
  <%= @patient.injury %>
</p>

<p>
  <strong>Observation:</strong>
  <%= @patient.observation %>
</p>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>